MVC_Final_ProjectCamp/Controllers/AdminCategoryController.cs
using Business.Concrete;
using Business.ValidationRules_FV;
using DataAccess.EntityFramework;
using Entities.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Final_ProjectCamp.Controllers
{
    public class AdminCategoryController : Controller
    {
        //EFCategoryDal Farklı çalışma alanlarından çalışabilmek için little touches .. :d
        CategoryManager cm = new CategoryManager(new EFCategoryDal());
        // GET: AdminCategory
        [Authorize(Roles="A")]//Authenticate olmadan görülme olmaz.
        public ActionResult Index()
        {
            var categoryValues = cm.fetchCategoryList();
            return View(categoryValues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAddBL(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        //kendine ait bir view olmayacak index üzerinden çağıralacak.
        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            cm.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            return View(categoryValue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MVC_Final_ProjectCamp/Views/AdminCategory/AddCategory.cshtml
@model Entities.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
<h1>Kategori Ekleme Sayfası</h1>
<br />
@*Başlangıç formu ekleme güncelleme yardımcısı HANGİ ACTİON,HANGİ CONTROLLER,FORM NE YAPACAK*@
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-info">Kaydet</button>

    </div>
}

MVC_Final_ProjectCamp/Views/AdminCategory/EditCategory.cshtml
@model Entities.Concrete.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Açıklaması")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
</div>
}

MVC_Final_ProjectCamp/Views/AdminCategory/Index.cshtml
@*kullanacaklarımı implemente ettim*@
@using Entities.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@*<!DOCTYPE html>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
<br />
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var index in Model)
    {
        <tr>
            <td>@index.CategoryID</td>
            <td>@index.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@index.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@index.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>

        </tr>

    }
</table>
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>